name: 'Welcome New Contributors'

on:
  issues:
    types: [unlabeled]

jobs:
  welcome-new-contributor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: 'Swift Bot'
        uses: tanmoysrt/bot@5be2ccde4960d152d5fac9e2edf7ef41dbcf01c5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
