name: 'Welcome New Contributors'

on:
  issues:
    types: [unlabeled]
  issue_comment:
    types: [created]

jobs:
  welcome-new-contributor:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
      - name: 'Swift Bot'
        uses: tanmoysrt/bot@add_update_command
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          triage-team-usernames: tanmoysrt
